= SimDisplay {badge-build_windows_service} {badge-build_for_unor3}
:toc:
:toc-title: 
:toclevels: 1
// Refs:
:url-workflows: https://github.com/fenegroni/simdisplay/workflows
:url-actions: https://github.com/fenegroni/simdisplay/actions
:badge-build_windows_service: image:{url-workflows}/Build Windows Service/badge.svg?branch=master[link={url-actions}]
:badge-build_for_unor3: image:{url-workflows}/Build for UnoR3/badge.svg?branch=master[link={url-actions}]

A simracing dashboard created using Arduino to show telemetry
from the racing simulator Assetto Corsa Competizione in real time.

Copyright (C) 2021  Filippo Erik Negroni

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

For a copy of the GNU General Public License see <https://www.gnu.org/licenses/>.

== Description

The SimDisplay project contains everything you need to build and run a real simracing dashboard
showing telemetry information from the racing simulator Assetto Corsa Competizione (ACC), in real time.

A Windows process reads data from ACC's shared memory telemetry and streams it to a supported device
running the embedded software which is also part of this project.

== Getting Started

=== Prerequisites

At a minimum, you will need:

* Windows 10;
* Visual Studio 2019 Community Edition;
* Arduino IDE 1.8;
* this code repository (download or clone);
* the components for the device you are going to build.

At the time of writing this README document, the only supported device is the Arduino Uno R3.

I have made a Fritzing diagram, exported as a breadboard wiring image.
I have also exported a BOM (bill of materials) as your shopping list for this project.

These are found in the https://github.com/fenegroni/simdisplay/tree/master/Device/UnoR3[`Device/UnoR3`] folder.

The README file in that folder has more detail.

=== Build the Service

Open the solution file `SimDisplay.sln` in folder
https://github.com/fenegroni/simdisplay/tree/master/Service/Windows[`Service/Windows`]
using Visual Studio 2019.

Build the solution which will create a Windows 64-bit Console application called SimDisplayCLI.

More detailed instructions and information can be found in the README file in the `Service` folder.

=== Build the device

and upload the firmware to your device

Under https://github.com/fenegroni/simdisplay/tree/master/Device/UnoR3[`Device/UnoR3`] you will find the Arduino IDE project file `UnoR3.ino`.

This is the embedded software that will run on the Arduino Uno R3 board microcontroller:
it receives telemetry data from the Windows host via the USB-to-serial interface
and drives all the connected LEDs and the Hitachi 16x2 dot matrix character display.

You must build and upload this software to the Arduino Uno R3, and you must connect
all the devices the board before being able to see telemetry data.

The Arduino IDE is free software and can be downloaded from `https://www.arduino.cc/en/Main/Software`
You can compile and upload the project to your Arduino board from the avialble Web Editor without
installing the IDE on your computer if you so wish.

For more information, refer to the README.adoc file in the folder https://github.com/fenegroni/simdisplay/tree/master/Device/UnoR3[`Device/UnoR3`].
