name: Build for UnoR3

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli lib install LiquidCrystal
      # Finally, we compile the sketch, using the FQBN that was set
      # in the build matrix.
      - name: Setup Zip tool
        uses: montudor/action-zip@v0.1.1
      - name: Zip SimDisplayProtocol library
        run: zip -r SimDisplayProtocol.zip SimDisplayProtocol
        working-directory: Device
      - name: Install SimDisplayProtocol library
        run: |
          arduino-cli config init
          arduino-cli config set library.enable_unsafe_install true
          arduino-cli lib install --zip-path Device/SimDisplayProtocol.zip
      - name: Compile Sketch
        run: arduino-cli compile --fqbn arduino:avr:uno Device/UnoR3/UnoR3.ino
