name: Build for UnoR3

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
      - name: Install LiquidCrystal library
        run: |
          arduino-cli lib install LiquidCrystal
      - name: Install simdisplay-proto library
        run: |
          arduino-cli config init
          arduino-cli config set library.enable_unsafe_install true
          arduino-cli lib install --git-url http://github.com/fenegroni/simdisplay-proto
      - name: Compile Sketch
        run: arduino-cli compile --fqbn arduino:avr:uno Device/UnoR3/UnoR3.ino
